name: Update NightCast Feed

on:

  workflow_dispatch:

  schedule:

    # هر 6 ساعت
    - cron: "0 */6 * * *"

  push:

    branches:

      - main

permissions:

  contents: write

jobs:

  update:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository

        uses: actions/checkout@v4

        with:

          fetch-depth: 0

      - name: Setup Node.js

        uses: actions/setup-node@v4

        with:

          node-version: 20


      - name: Install Dependencies

        run: npm install

      - name: Show Node Version

        run: |

          node -v

          npm -v

      - name: Run Feed Generator

        run: |

          echo "=============================="

          echo "Running NightCast Generator..."

          echo "=============================="

          node scripts/parser.js

      - name: Verify Output Files

        run: |

          test -f data/feed.json

          test -f data/feed-lite.json

          test -f data/raw-feed.json

          test -f data/search.json

          test -f data/rss.xml

          test -f data/sitemap-feed.xml

      - name: Show Generated Files

        run: |

          echo "=============================="

          ls -lah data/

          echo "=============================="



                - name: Commit Changes

        run: |

          git config --global user.name "github-actions[bot]"

          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/

          git diff --cached --quiet && echo "No changes to commit." || git commit -m "Update NightCast Feed"

      - name: Push Changes

        if: success()

        uses: ad-m/github-push-action@master

        with:

          github_token: ${{ secrets.GITHUB_TOKEN }}

          branch: main

      - name: Finished

        run: |

          echo ""

          echo "===================================="

          echo " NightCast Feed Updated Successfully "

          echo "===================================="

          echo ""




          

          
